package vista;

import controlador.PedidoControlador;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.PedidoModelo;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Tiririn
 */
public class Pedidos extends javax.swing.JInternalFrame {

        DefaultTableModel model = new DefaultTableModel();
       PedidoModelo p = new PedidoModelo();

           ArrayList<PedidoModelo> listapedidos = new ArrayList<>();

           public void setModel() {
        String[] cabecera = {"Nº1.", "Id Pedido", "Cedula Cliente", "Fecha Pedido", "Descripciòn", "Cantidad", "Precio  Total"};
        model.setColumnIdentifiers(cabecera);
        tblPostullante.setModel(model);

    }
         public void setDatos() {
        Object[] datoFila = new Object[model.getColumnCount()];
        int nro = 1;
        
       
        for (PedidoModelo puntero : listapedidos) {
            datoFila[0] = nro;
            datoFila[1] = puntero.getIdPedido();
            datoFila[2] = puntero.getIdCliente();
            datoFila[3] = puntero.getFechaPedido();
            datoFila[4] = puntero.getDescripcion();
            datoFila[5] = puntero.getCantidad();
            datoFila[6] = puntero.getPrecioTotal();
            nro++;
            model.addRow(datoFila);
        }

    }
           
    public Pedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPostullante = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jblCedula.setText("Cedula");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblPostullante.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, null), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));
        tblPostullante.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tblPostullante.setName("TABLA POSTULANTE"); // NOI18N
        tblPostullante.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblPostullanteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(tblPostullante);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnBuscar)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
                String cedula = txtCedula.getText();
        PedidoControlador pC = new PedidoControlador();
        ArrayList<Object[]> listaFilas = pC.buscarPostulante(cedula);
        for (Object[] listaFila : listaFilas) 
         listapedidos.add(p);
        this.setDatos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblPostullanteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblPostullanteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPostullanteAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jblCedula;
    private javax.swing.JTable tblEmpleador;
    private javax.swing.JTable tblEmpleador1;
    private javax.swing.JTable tblPostullante;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
